name: deploy
on:
  push:
    branches:
      - main

jobs:
  build:
    name: build & deploy
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout
      uses: actions/checkout@v1

    - name: install
      uses: borales/actions-yarn@v2.3.0
      with:
          cmd: install

    - name: build
      uses: borales/actions-yarn@v2.3.0
      with:
          cmd: build
      env:
        REACT_APP_OPENWEATHER_API_KEY: ${{ secrets.REACT_APP_OPENWEATHER_API_KEY }}
   
    - name: test:ci 
      uses: borales/actions-yarn@v2.3.0
      with:
          cmd: test:ci
      

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: build
